//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class addressdetail
    {
        public int addressDetail_id { get; set; }
        public string addressDetail_address { get; set; }
        public Nullable<int> addressDetail_userId { get; set; }
        public Nullable<int> addressDetail_postCode { get; set; }
    
        public virtual user user { get; set; }
    }
}
