//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNET.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class farmfreshEntities : DbContext
    {
        public farmfreshEntities()
            : base("name=farmfreshEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<blogs> blogs { get; set; }
        public virtual DbSet<category> category { get; set; }
        public virtual DbSet<district> district { get; set; }
        public virtual DbSet<orderitem> orderitem { get; set; }
        public virtual DbSet<orders> orders { get; set; }
        public virtual DbSet<paragraph> paragraph { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<provice> provice { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
