//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNET.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class farmfreshEntities : DbContext
    {
        public farmfreshEntities()
            : base("name=farmfreshEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<blog> blogs { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<district> districts { get; set; }
        public virtual DbSet<orderitem> orderitems { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<paragraph> paragraphs { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<provice> provices { get; set; }
        public virtual DbSet<review> reviews { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
