//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class review
    {
        public string review_id { get; set; }
        public string review_createBy { get; set; }
        public byte[] review_createAt { get; set; }
        public Nullable<int> review_ratingStar { get; set; }
        public string review_content { get; set; }
        public string review_productId { get; set; }
    
        public virtual product product { get; set; }
        public virtual user user { get; set; }
    }
}
