//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNET.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Role_Quyen
    {
        public int Id { get; set; }
        public Nullable<int> role_id { get; set; }
        public string quyen_id { get; set; }
        public string Ghi_chu { get; set; }
    
        public virtual Quyen Quyen { get; set; }
        public virtual role role { get; set; }
    }
}
